<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit300887f24d29c97f4d20cbb0c7749b8d
{
    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'Upload' => 
            array (
                0 => __DIR__ . '/..' . '/codeguy/upload/src',
            ),
        ),
        'S' => 
        array (
            'Slim' => 
            array (
                0 => __DIR__ . '/..' . '/slim/slim',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit300887f24d29c97f4d20cbb0c7749b8d::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
